//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id_User { get; set; }
        public int Id_Ticket { get; set; }
        public bool Tea { get; set; }
        public bool Bedding { get; set; }
        public decimal Cost { get; set; }
        public Nullable<byte> Id_Facility { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
