//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public Connection()
        {
            this.Route = new HashSet<Route>();
            this.Train = new HashSet<Train>();
        }
    
        public int Id { get; set; }
        public short Id_Departure_Station { get; set; }
        public short Id_Arrival_Station { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Route> Route { get; set; }
        public virtual ICollection<Train> Train { get; set; }
    }
}
