//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public byte Id { get; set; }
        public string Descript { get; set; }
        public byte Discount { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
