//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Connection = new HashSet<Connection>();
            this.Connection1 = new HashSet<Connection>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Connection> Connection { get; set; }
        public virtual ICollection<Connection> Connection1 { get; set; }
    }
}
