//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public byte Place_Number { get; set; }
        public int Id_Route { get; set; }
        public int Id_Wagon { get; set; }
        public System.DateTime Departure_Date { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Route Route { get; set; }
        public virtual Wagon Wagon { get; set; }
    }
}
