//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public Train()
        {
            this.Wagon = new HashSet<Wagon>();
        }
    
        public short Id { get; set; }
        public string Code { get; set; }
        public int Id_Connection { get; set; }
    
        public virtual Connection Connection { get; set; }
        public virtual ICollection<Wagon> Wagon { get; set; }
    }
}
