//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Booking = new HashSet<Booking>();
            this.Payments = new HashSet<Payments>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Phone_Number { get; set; }
        public string Passport_Num { get; set; }
        public string Address { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public byte Id_User_Role { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual User_Role User_Role { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
