//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon
    {
        public Wagon()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public byte Number { get; set; }
        public short Id_Train { get; set; }
        public byte Id_Wagon_Type { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual Train Train { get; set; }
        public virtual Wagon_Type Wagon_Type { get; set; }
    }
}
