//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayTicketBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon_Type
    {
        public Wagon_Type()
        {
            this.Wagon = new HashSet<Wagon>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
    
        public virtual ICollection<Wagon> Wagon { get; set; }
    }
}
